# This workflow will run cypress tests in this repo

name: Cypress headless browser tests

on: workflow_dispatch

jobs:
  headless-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '14.x.x'

    - name: Install dependencies
      run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        headed: true

    - name: Upload test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Storyblok Cypress headless tests report
        path: test-reports    
      
    

   
    


          

      


 
